### ISSUE TITLE
Bot not working; no longer retrieves information

### ISSUE THREAD

**Issue by switch-stuff** [reswitched/HacVersionListBot#1]
Due to Nintendo updating auth requirements, the bot gets 403 Access Denied when attempting to contact Shogun, therefore it is unable to display the title metadata.

**Comment by SciresM** [comment]
I'm currently too busy working on Atmosphere to update HacVLBot's repo in a way that doesn't use shitty hacks -- I'll put it on the long-term todo list though.

**Comment by Falco20019** [comment]
You could just briefly describe what the problem is and I would do a PR. Looked into it myself right now and although I used ShopN cert I was denied. Haven't had time to look into it more yesterday. So is ShopN using the console cert now or is it checking for other features like user-agent and so on?

You seem to know what it is, since your Twitter Bot works again :) So if it's just about don't releasing hacks...

**Comment by switch-stuff** [comment]
@Falco20019  I'm assuming that the python script downloads a game's control NCA and returns the title from the game's control.nacp, so you'd use your client certificate, not ShopN.

**Comment by Falco20019** [comment]
Possible. Would be enough if @SciresM posts hit python script to pastebin or just makes a screenshot so that we can port it.

**Comment by switch-stuff** [comment]
@Falco20019 It's pretty simple to make though.
Say we use Odyssey 1.0.1 as an example (I use this one every time, the title ID is easy to remember)
All of the following requests should use this User-Agent:
"NintendoSDK Firmware/5.1.0-0 (platform:NX; did:[DEVICE ID]; eid:lp1)"
Send a HEAD request to https://atum.hac.lp1.d4c.nintendo.net/a/d/0100000000010000/65536
Read the "x-nintendo-content-id" response header, in this case it's "1f7f7a0694ad74f666873862629bbcb9"
Send a GET request to https://atum.hac.lp1.d4c.nintendo.net/c/a/**(ID)**
That will download the meta NCA.
Decrypt the meta NCA, and extract its PFS0 partition. You will get a **c**o**n**tent **m**e**t**adata file.
The number of data listings is specified at 0x10 in the CNMT. 
Parse all data listings, then use the one with type 0x3 (Control).
Send a GET request to https://atum.hac.lp1.d4c.nintendo.net/c/c/(0x20-0x30 of content listing)
That downloads the control NCA.
Next, decrypt that NCA, and extract the RomFS.
Read from the extracted control.nacp (the info listing, similar to the 3DS' shaking my damn head format) file, usually the first entry will suffice, but in the case of EUR or foreign releases you will need to continue reading until the first entry with the game's title.
Bingo! That's the game's title.

P.S. If you wanna be extra cool, you can also get it to send out the icon, the .dat icons are unfortunately encoded as JPEG (although DCT blocking artefacts are minimal due to Nintendo encoding the image at very high quality).

**Comment by Falco20019** [comment]
Still, this server wants the console key instead of shopn key, right? I hoped to can avoid having to dump my NAND and using my own consoles one

**Comment by switch-stuff** [comment]
Yeah, console-unique stuff

**Comment by switch-stuff** [comment]
Shogun is allowing invalid requests again, so I'll close this issue for now.

**Comment by Falco20019** [comment]
Interesting that they would only change it for E3 (maybe for preventing leaks which didn’t help). Or it could be a trap to get people into using it again for recording purposes.
